name: neopop
description: NeoPop is CRED's inbuilt library for using NeoPop components in your app.
version: 1.0.2
homepage: https://github.com/CRED-CLUB/neopop-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
