name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: download dependencies
        run: flutter pub get

      - name: run flutter format
        run: flutter format --set-exit-if-changed .

  analyze:
    name: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: download dependencies
        run: flutter pub get

      - name: run flutter Analyze
        run: flutter analyze